### ISSUE TITLE
sys.setdefaultencoding() is not valid for newer versions of python

### ISSUE THREAD

**Issue by caranha** [ALife-Newsletter/Newsletter#10]
The above command does not work for python > 3.4, so we should probably find an alternative way to fix that.

Is the CI running on python 2?

**Comment by mitsuyoshi-yamazaki** [comment]
I removed the function in the pull request above. Please close this if you don't have any other problems about Python version.

**Comment by caranha** [comment]
Ah, I forgot about this comment. So the code runs correctly on newer python versions? (no time to check right now)

**Comment by mitsuyoshi-yamazaki** [comment]
yes, once you install pyenv, it automatically read the specified python version

https://github.com/ALife-Newsletter/Newsletter/pull/11
